#! /bin/bash
echo ............................................................
echo Installing npm dependencies
echo ............................................................
npm install
echo Done!
echo ............................................................
echo Updating npm dependencies
echo ............................................................
npm update
echo Done!
echo ............................................................
echo Installing bower dependencies
echo ............................................................
bower install
echo Done!
echo ............................................................
echo Updating bower dependencies
echo ............................................................
bower update
echo Done!
echo ............................................................
echo Installing composer dependencies
echo ............................................................
composer install
echo Done!
echo ............................................................
echo Updating composer dependencies
echo ............................................................
composer update
echo Done!
echo ............................................................
echo Composer dumpautoload
echo ............................................................
composer dumpautoload
echo Done!
echo ............................................................